### ISSUE TITLE
Home Screen

### ISSUE THREAD

**Issue by jemaie** [sopra-fs22-group-09/basically-wordle-backend#17]
**Story:** As a player, I want to have an overview of possible actions in order to choose a desired one.

**Acceptance Criteria:**
- [x] sopra-fs22-group-09/basically-wordle-frontend#11
- [x] sopra-fs22-group-09/basically-wordle-frontend#12
- [x] sopra-fs22-group-09/basically-wordle-frontend#13
- [x] sopra-fs22-group-09/basically-wordle-frontend#10
- [x] sopra-fs22-group-09/basically-wordle-backend#52

**Development Tasks:**
- [x] sopra-fs22-group-09/basically-wordle-frontend#43

**Priority:** critical
**Author:** SoPra Group 9
**Estimate:** 4h
