### ISSUE TITLE
Lobby

### ISSUE THREAD

**Issue by Flash1232** [sopra-fs22-group-09/basically-wordle-backend#2]
**Story:** As a player I want to be able to create a lobby so that other players can join my game.

**Acceptance Criteria:**
- [x] sopra-fs22-group-09/basically-wordle-frontend#8
- [x] sopra-fs22-group-09/basically-wordle-backend#61
- [ ] sopra-fs22-group-09/basically-wordle-backend#64
- [ ] sopra-fs22-group-09/basically-wordle-backend#67
- [x] sopra-fs22-group-09/basically-wordle-backend#68
- [x] sopra-fs22-group-09/basically-wordle-backend#69
- [x] sopra-fs22-group-09/basically-wordle-backend#70
- [x] sopra-fs22-group-09/basically-wordle-backend#71

**Dev Tasks**
- [x] #151
- [x] #156

**Priority:** critical
**Author:** SoPra Group 9
**Estimate:** 16h
