### ISSUE TITLE
Fix game & lobby stuff and other minor bugs

### ISSUE THREAD

**Issue by Flash1232** [sopra-fs22-group-09/basically-wordle-backend#210]
- [x] #240
- [x] #241
- [x] #242
- [x] Lobby subscription should only be started after subscribe mutation returns (using e.g. `skip: loading || !called` attribute)
- [x] #243
- [x] sopra-fs22-group-09/basically-wordle-frontend#155
- [x] #237
- [x] Lobby subscription should reject players if lobby full
- [x] same for gameStatus
- [x] #239
- [x] sopra-fs22-group-09/basically-wordle-frontend#164
- [x] sopra-fs22-group-09/basically-wordle-frontend#165
- [x] sopra-fs22-group-09/basically-wordle-backend#228
- [x] sopra-fs22-group-09/basically-wordle-backend#229
- [x] sopra-fs22-group-09/basically-wordle-backend#230
- [x] sopra-fs22-group-09/basically-wordle-backend#231
- [x] sopra-fs22-group-09/basically-wordle-backend#233
