### ISSUE TITLE
Game Base

### ISSUE THREAD

**Issue by Flash1232** [sopra-fs22-group-09/basically-wordle-backend#22]
**Story:** As a player I want to have a base of the game so that I can play any game mode with other lobby members.

**Acceptance Criteria:**

- [x] sopra-fs22-group-09/basically-wordle-backend#84
- [x] sopra-fs22-group-09/basically-wordle-frontend#99
  - [x] sopra-fs22-group-09/basically-wordle-frontend#100
  - [x] sopra-fs22-group-09/basically-wordle-frontend#101
  - [x] sopra-fs22-group-09/basically-wordle-frontend#102
  - [x] sopra-fs22-group-09/basically-wordle-frontend#103
- [x] sopra-fs22-group-09/basically-wordle-frontend#9
- [x] sopra-fs22-group-09/basically-wordle-backend#91
- [x] sopra-fs22-group-09/basically-wordle-backend#92
- [x] sopra-fs22-group-09/basically-wordle-backend#93
- [x] sopra-fs22-group-09/basically-wordle-backend#94

**Development Tasks**:
- [x] sopra-fs22-group-09/basically-wordle-backend#140
- [x] sopra-fs22-group-09/basically-wordle-frontend#68
  - [x] sopra-fs22-group-09/basically-wordle-frontend#97
  - [x] sopra-fs22-group-09/basically-wordle-frontend#98
- [x] sopra-fs22-group-09/basically-wordle-backend#152
- [x] sopra-fs22-group-09/basically-wordle-backend#153
- [x] sopra-fs22-group-09/basically-wordle-backend#154
- [x] sopra-fs22-group-09/basically-wordle-backend#157
- [x] sopra-fs22-group-09/basically-wordle-backend#158

**Priority:** critical
**Author:** SoPra Group 9
**Estimate:** 12h
