### ISSUE TITLE
Game Customization

### ISSUE THREAD

**Issue by Flash1232** [sopra-fs22-group-09/basically-wordle-backend#3]
**Story:** As a player I want to be able to customize the game so that I can choose game mode and difficulty.

**Acceptance Criteria:**

- [x] sopra-fs22-group-09/basically-wordle-backend#72
  - [x] sopra-fs22-group-09/basically-wordle-backend#73
  - [x] sopra-fs22-group-09/basically-wordle-backend#74
  - [ ] sopra-fs22-group-09/basically-wordle-frontend#15
  - [x] sopra-fs22-group-09/basically-wordle-backend#76
- [ ] sopra-fs22-group-09/basically-wordle-backend#77
- [x] sopra-fs22-group-09/basically-wordle-backend#78
- [ ] sopra-fs22-group-09/basically-wordle-backend#79

**Development Tasks**:
- [ ] TBD...

**Priority:** critical
**Author:** SoPra Group 9
**Estimate:** 24h
