### ISSUE TITLE
Login and Password Reset

### ISSUE THREAD

**Issue by Flash1232** [sopra-fs22-group-09/basically-wordle-backend#6]
**Story:** As a player I want to be able to log in to the application so that I can use it.

**Acceptance Criteria:**

- [x] sopra-fs22-group-09/basically-wordle-backend#37
- [x] sopra-fs22-group-09/basically-wordle-backend#38
- [x] sopra-fs22-group-09/basically-wordle-backend#39
- [x] sopra-fs22-group-09/basically-wordle-frontend#3
- [x] sopra-fs22-group-09/basically-wordle-frontend#14
- [ ] sopra-fs22-group-09/basically-wordle-backend#42
- [x] sopra-fs22-group-09/basically-wordle-backend#43

**Development Tasks:**

- [x] #105
- [ ] #117
- [x] #119
- [x] #155
- [x] #206
- [x] #207

**Priority:** critical
**Author:** SoPra Group 9
**Estimate:** 6h
