### ISSUE TITLE
In-Game Chat

### ISSUE THREAD

**Issue by polatmete** [sopra-fs22-group-09/basically-wordle-backend#8]
**Story:** As a user I want to be able to send (pre-defined) messages and emojis to other players.

**Acceptance Criteria:**

- [x] sopra-fs22-group-09/basically-wordle-frontend#18
- [x] sopra-fs22-group-09/basically-wordle-backend#81
- [x] sopra-fs22-group-09/basically-wordle-frontend#17
- [x] sopra-fs22-group-09/basically-wordle-frontend#16

**Priority:** medium
**Author:** SoPra Group 9
**Estimate:** 8h

**Comment by jemaie** [comment]
Couldn't be completed since we lost a group member in the beginning.
Please find further explanation in the group report.
