### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by bzns** [sopra-fs22-group-09/basically-wordle-backend#9]
**Story:** As a user I want to be able to register as a new player to play the game

**Acceptance Criteria:**

- [x] sopra-fs22-group-09/basically-wordle-backend#60
- [x] sopra-fs22-group-09/basically-wordle-frontend#7
- [x] sopra-fs22-group-09/basically-wordle-frontend#5
- [x] sopra-fs22-group-09/basically-wordle-frontend#6
- [x] sopra-fs22-group-09/basically-wordle-backend#66

**Priority:** critical
**Author:** SoPra Group 9
**Estimate:** 6h
